


male_prompts = [
    "symmetry!!! closeup portrait of a cyborg transparent <concept>, fashion cyber jumpsuit with big shoulder pads, cinematic light, backlight, windy, teal orange, smoke trails, mist, by gerald brom, by mikhail vrubel, by peter elson, muted colors, extreme detail, trending on artstation, 8 k ",
    "human 3 d by pantokrator, beautiful sexy <concept> head made of mech mask rendered in unreal engine, nanotechnology, golden cyberntic vessels coming from core processor, contrast, painted by david burliuk | bernard buffet | carne griffiths | stanislaw lem ",
    "a simple painting of a <concept> by Android Jones and M. C. Escher collaboration",
    "Very very very very highly detailed epic portrait photo of <concepts> with venetian mask, intricate, dystopian, sci-fi, extremely detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, intimidating lighting, incredible art by Tokujin Yoshioka and Anton Pieck",
    "the <concept> head sculpture made from wire ",
    "an accidental selfies taken by a <concept> caveman in 10000 bc, Canon EOS R3, f/1.4, ISO 200, 1/160s, 8K, RAW, unedited, symmetrical balance, in-frame",
    "a selfie taken by a <concept> caveman in 10000 bc, Canon EOS R3, f/1.4, ISO 200, 1/160s, 8K, RAW, unedited, symmetrical balance, in-frame",
    "a sympathetic <concept> caveman, character portrait by greg rutkowski, craig mullins ",
    "young <concept> warrior marching toward the viewer, male, muscular, green eyes!!!!, straight nose!!!!!, beard, detailed face, thighs!!!!! gorgeous, amazing, toned, intricate, highly detailed, painting by Gaston Bussiere, Craig Mullins",
    "an autochrome realistic, supersharp, photographic portrait of <concept> (vincent van gogh), by thomas russel shallow depth of field ",
    "the <concept>, the logician, pride, unique perspectives, vigorous intellect, mysteries of the universe, influential philosopher, scientist, lord of the rings, tattoo, decorated ornaments by carl spitzweg, ismail inceoglu, vdragan bibin, hans thoma, greg rutkowski, alexandros pyromallis, perfect face, fine details, realistic shaded ",
    "hyper detailed comic illustration of a beautiful flower growing out of the head of a young mixed race <concept> explorer's head, cyberpunk headpiece, intricate details, vibrant, negative space, quadrant framing, by Josan Gonzalez and Geof Darrow, highly detailed, 8k wallpaper",
    "portrait of 6 armed Monster <concept> intricate abstract. intricate artwork. by Tooth Wu, wlop, beeple, dan mumford. mulholland drive by david lynch, dune by david lynch, octane render, trending on artstation, greg rutkowski very coherent symmetrical artwork. cinematic, hyper realism, high detail, octane render, 8k, iridescent accents",
    "<concept> masterpiece, beautiful eyes, red, golden halo behind her head, red wires wrap around, by Edgar Maxence and Ross Tran, Zdzisław Beksiński, and Michael Whelan, distant, gustav dore, H.R. Giger, 8k, octane render",
    "highly detailed 3D render of <concept>, by greg rutkowski, craig mulli",
    "cubist artwork of a <concept>, trending on Artstation",
    "HD DSLR photograph of a <concept> in front of the great pyramid of giza",
    "a photo of the <concept> on the summit of mount Kilimanjaro, Tanzania, Africa, 4k, nature photography",
    "<concept> taking a selfie in front of the great pyramid of gizeh, Egypt, 4k, nature photography",
    "a photo of <concept> taking a selfie on the medieval ship of columbus, 4k, detailed face",
    "a photo of a <concept> caveman, lots of hair",
    "portrait of bird <concept> by Beksinski",
    "stunning masterpiece portrait of <concept> by Beksinski",
    "Very detailed epic central composition photo of <concept> face, intricate, dystopian, sci-fi, extremely detailed, digital painting, smooth, sharp focus, illustration, intimidating lighting, incredible art by Brooke Shaden, artstation, concept art, Octane render in Maya and Houdini",
    "an artwork masterpiece of a <concept> as the Rock",
    "a photo of <concept> as a sexy pro wrestler",
    "a funny artwork of a <concept> looking like a vegetable, trending on Artstation",
    "<concept> as caesar of the roman empire taking a selfie on his horse before the city of rome",
    "a photo of a <concept> as a sexy mermaid",
    "a photo of a <concept> defending his phd thesis",
    "a <concept> wearing sun glasses tennis ball monster, <concept> tennis ball head, monster teeth, colorful, chalk digital art, fantasy, magic, chalk, trending on artstation, ultra detailed, professional illustration by basil gogos ",
    "portrait of a cute <concept> werewolf with big glowing eyes, highly detailed, digital painting, dark retrowave, art by Stanley Lau and Artgerm and magali villeneuve and Alphonse Mucha, artstation, octane render, cgsociety",
    "a <concept> man wolf centaur, has the head of a timber wolf, torso of a <concept> man, and body of a wolf, standing on four legs, covered in fur, highly realistic, Rick Baker style, photoreal, studio lighting",
    "an extremely psychedelic portrait of the <concept> as the joker, surreal, lsd, face, detailed, intricate, elegant, lithe, highly detailed, digital oth, sharp focus, illustration, ",
    "halfturn portrait of a big crystal <concept> face made of crystals half - turn, bottom view, ominous, intricate, studio, art by anthony macbain + greg rutkowski + alphonse mucha, concept art, 4 k, sharp focus",
    "a beautiful <concept> face draped in fat cluttered  inflated wires in the style of peter gric hd",
    "dramatic portrait painting of <concept> with black mandelbrot fractal instead of face, in style of zdzisław beksinski, horror, body horror, dark, disturbing, hyper detqiled",
    "complex 3d render of <concept>, a beautiful porcelain cyber robot ai <concept> face, blue and gold, fractal veins, vegetal dragon cyborg, 1 5 0 mm, beautiful natural soft light, rim light, silver gold details, roots, fine lace, mandelbot fractal, anatomical, glass, facial muscles, elegant, ultra detailed, metallic armor, octane render",
    "engineer prometheus <concept> face by Artgerm, xenomorph alien, highly detailed, symmetrical long head, smooth marble surfaces, detailed ink illustration, raiden metal gear, cinematic smooth stone, deep aesthetic, concept art, post process, 4k, carved marble texture and silk cloth, latex skin, highly ornate intricate details, prometheus, evil, moody lighting, hr geiger, hayao miyazaki, indsutrial Steampunk",
    "hyperrealistic mixed media image of unimaginable incomprehensible horror <concept> ripping apart space and time, stunning 3 d render inspired art by greg rutkowski and xiang duan and thomas eakes, hp lovecraft, perfect symmetry, flesh texture, realistic, highly detailed attributes and atmosphere, dim volumetric cinematic lighting, 8 k octane detailed render, post - processing, masterpiece, ",
    "A scene from a horror movie, with a close up of a <concept> victim's face, covered in blood, with the murderer's hand reaching out from the darkness, by Justin Gerard and Greg Rutkowski, highly detailed, sharp focus, elegant, illustration, 15mm lens, 4K",
    "no fears, <concept>, okay one fear, highly-detailed, elegant, dramatic lighting, artstation, 4k, cinematic landscape by Dave McKean",
    "screaming cyberpunk <concept>, wires, machines by emil melmoth zdzislaw belsinki craig mullins yoji shinkawa realistic render ominous detailed photo atmospheric by jeremy mann francis bacon and agnes cecile ink drips paint smears digital glitches glitchart ",
    "portrait of a cosmic <concept> god, body made out of stars and galaxies and cosmic energy, intricate, headshot, highly detailed, digital painting, artstation, concept art, sharp focus, cinematic lighting, illustration, art by artgerm and greg rutkowski, alphonse mucha, cgsociety",
    "portrait of a cosmic <concept> god, body made out of stars and galaxies and cosmic energy, intricate, headshot, highly detailed, digital painting, artstation, concept art, sharp focus, cinematic lighting, illustration, art by artgerm and greg rutkowski, alphonse mucha, cgsociety",
    "symmetry!!! closeup portrait of a cyborg transparent <concept>, fashion cyber jumpsuit with big shoulder pads, cinematic light, backlight, windy, teal orange, smoke trails, mist, by gerald brom, by mikhail vrubel, by peter elson, muted colors, extreme detail, trending on artstation, 8 k ",
    "human 3 d by pantokrator, beautiful sexy <concept> head made of mech mask rendered in unreal engine, nanotechnology, golden cyberntic vessels coming from core processor, contrast, painted by david burliuk | bernard buffet | carne griffiths | stanislaw lem ",
    "a simple painting of <concept> by Android Jones and M. C. Escher collaboration",
    "Very very very very highly detailed epic portrait photo of <concepts> with venetian mask, intricate, dystopian, sci-fi, extremely detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, intimidating lighting, incredible art by Tokujin Yoshioka and Anton Pieck",
    "<concept> head sculpture made from wire ",
    "an accidental selfies taken by a <concept> caveman in 10000 bc, Canon EOS R3, f/1.4, ISO 200, 1/160s, 8K, RAW, unedited, symmetrical balance, in-frame",
    "a selfie taken by a <concept> caveman in 10000 bc, Canon EOS R3, f/1.4, ISO 200, 1/160s, 8K, RAW, unedited, symmetrical balance, in-frame",
    "a sympathetic <concept> caveman, character portrait by greg rutkowski, craig mullins ",
    "young <concept> warrior marching toward the viewer, male, muscular, green eyes!!!!, straight nose!!!!!, beard, detailed face, thighs!!!!! gorgeous, amazing, toned, intricate, highly detailed, painting by Gaston Bussiere, Craig Mullins",
    "an autochrome realistic, supersharp, photographic portrait of <concept> (vincent van gogh), by thomas russel shallow depth of field ",
    "<concept>, the logician, pride, unique perspectives, vigorous intellect, mysteries of the universe, influential philosopher, scientist, lord of the rings, tattoo, decorated ornaments by carl spitzweg, ismail inceoglu, vdragan bibin, hans thoma, greg rutkowski, alexandros pyromallis, perfect face, fine details, realistic shaded ",
    "hyper detailed comic illustration of a beautiful flower growing out of the head of a young mixed race <concept> explorer's head, cyberpunk headpiece, intricate details, vibrant, negative space, quadrant framing, by Josan Gonzalez and Geof Darrow, highly detailed, 8k wallpaper",
    "portrait of 6 armed Monster <concept> intricate abstract. intricate artwork. by Tooth Wu, wlop, beeple, dan mumford. mulholland drive by david lynch, dune by david lynch, octane render, trending on artstation, greg rutkowski very coherent symmetrical artwork. cinematic, hyper realism, high detail, octane render, 8k, iridescent accents",
    "<concept> masterpiece, beautiful eyes, red, golden halo behind her head, red wires wrap around, by Edgar Maxence and Ross Tran, Zdzisław Beksiński, and Michael Whelan, distant, gustav dore, H.R. Giger, 8k, octane render",
    "highly detailed 3D render of <concept>, by greg rutkowski, craig mulli",
    "cubist artwork of <concept>, trending on Artstation",
    "HD DSLR photograph of <concept> in front of the great pyramid of giza",
    "a photo of <concept> on the summit of mount Kilimanjaro, Tanzania, Africa, 4k, nature photography",
    "<concept> taking a selfie in front of the great pyramid of gizeh, Egypt, 4k, nature photography",
    "a photo <concept> taking a selfie on the medieval ship of columbus, 4k, detailed face",
    "a photo of <concept> caveman, lots of hair",
    "portrait of bird <concept> by Beksinski",
    "stunning masterpiece portrait of <concept> by Beksinski",
    "Very detailed epic central composition photo of <concept> face, intricate, dystopian, sci-fi, extremely detailed, digital painting, smooth, sharp focus, illustration, intimidating lighting, incredible art by Brooke Shaden, artstation, concept art, Octane render in Maya and Houdini",
    "an artwork masterpiece of <concept> as the Rock",
    "a photo of <concept> as a sexy pro wrestler",
    "a funny artwork of a <concept> looking like a vegetable, trending on Artstation",
    "<concept> as caesar of the roman empire taking a selfie on his horse before the city of rome",
    "a photo of <concept> as a sexy mermaid",
    "a photo of <concept> defending his phd thesis",
    "<concept> wearing sun glasses tennis ball monster, <concept> tennis ball head, monster teeth, colorful, chalk digital art, fantasy, magic, chalk, trending on artstation, ultra detailed, professional illustration by basil gogos ",
    "portrait of a cute <concept> werewolf with big glowing eyes, highly detailed, digital painting, dark retrowave, art by Stanley Lau and Artgerm and magali villeneuve and Alphonse Mucha, artstation, octane render, cgsociety",
    "<concept> man wolf centaur, has the head of a timber wolf, torso of <concept> man, and body of a wolf, standing on four legs, covered in fur, highly realistic, Rick Baker style, photoreal, studio lighting",
    "an extremely psychedelic portrait of the <concept> as the joker, surreal, lsd, face, detailed, intricate, elegant, lithe, highly detailed, digital oth, sharp focus, illustration, ",
    "halfturn portrait of a big crystal <concept> face made of crystals half - turn, bottom view, ominous, intricate, studio, art by anthony macbain + greg rutkowski + alphonse mucha, concept art, 4 k, sharp focus",
    "a beautiful <concept> face draped in fat cluttered  inflated wires in the style of peter gric hd",
    "dramatic portrait painting of <concept> with black mandelbrot fractal instead of face, in style of zdzisław beksinski, horror, body horror, dark, disturbing, hyper detqiled",
    "complex 3d render of <concept>, a beautiful porcelain cyber robot ai <concept> face, blue and gold, fractal veins, vegetal dragon cyborg, 1 5 0 mm, beautiful natural soft light, rim light, silver gold details, roots, fine lace, mandelbot fractal, anatomical, glass, facial muscles, elegant, ultra detailed, metallic armor, octane render",
    "engineer prometheus <concept> face by Artgerm, xenomorph alien, highly detailed, symmetrical long head, smooth marble surfaces, detailed ink illustration, raiden metal gear, cinematic smooth stone, deep aesthetic, concept art, post process, 4k, carved marble texture and silk cloth, latex skin, highly ornate intricate details, prometheus, evil, moody lighting, hr geiger, hayao miyazaki, indsutrial Steampunk",
    "hyperrealistic mixed media image of unimaginable incomprehensible horror <concept> ripping apart space and time, stunning 3 d render inspired art by greg rutkowski and xiang duan and thomas eakes, hp lovecraft, perfect symmetry, flesh texture, realistic, highly detailed attributes and atmosphere, dim volumetric cinematic lighting, 8 k octane detailed render, post - processing, masterpiece, ",
    "A scene from a horror movie, with a close up of <concept> victim's face, covered in blood, with the murderer's hand reaching out from the darkness, by Justin Gerard and Greg Rutkowski, highly detailed, sharp focus, elegant, illustration, 15mm lens, 4K",
    "no fears, <concept>, okay one fear, highly-detailed, elegant, dramatic lighting, artstation, 4k, cinematic landscape by Dave McKean",
    "screaming cyberpunk <concept>, wires, machines by emil melmoth zdzislaw belsinki craig mullins yoji shinkawa realistic render ominous detailed photo atmospheric by jeremy mann francis bacon and agnes cecile ink drips paint smears digital glitches glitchart ",
    "portrait of a cosmic <concept> god, body made out of stars and galaxies and cosmic energy, intricate, headshot, highly detailed, digital painting, artstation, concept art, sharp focus, cinematic lighting, illustration, art by artgerm and greg rutkowski, alphonse mucha, cgsociety",
    "portrait of a cosmic <concept> god, body made out of stars and galaxies and cosmic energy, intricate, headshot, highly detailed, digital painting, artstation, concept art, sharp focus, cinematic lighting, illustration, art by artgerm and greg rutkowski, alphonse mucha, cgsociety",
    "abstract expressionism oil painting intertwined with a human <concept> head, spray paint texture, drips, impasto paint, 3 d graffiti texture, brushstrokes, abstract, highly detailed, hyperealistic fresh paint, harmonious, chaotic, colorfull, in the style of alphonse mucha ",
    "a portrait of a <concept> character in a scenic environment by robert hagan, hyperdetailed, cyberpunk, cool, trending on artstation ",
    "a portrait of <concept> in a scenic environment by robert hagan, hyperdetailed, cyberpunk, cool, trending on artstation ",
    "<concept> human 3 d by pantokrator, beautiful sexy <concept>    head made of mech mask rendered in unreal engine, nanotechnology, golden cyberntic vessels coming from core processor, contrast, painted by david burliuk | bernard buffet | carne griffiths | stanislaw lem ",
    "abstract expressionist mid shot portrait of a beautiful <concept>, body fully covered of very thick iridescent black impasto paint and iridescent black acrylic pour and iridescent black colour powder explosion and splashing iridescent black paint and dripping iridescent black paint and flying iridescent black paint chunks, eyes closed or not visible, expressing strong emotions, motion blur, hyperrealistic, intricate art photography, anatomically correct, realistic crisp textures, 1 6 k ",
    "<concept> faces melting liquid acrylic painting abstract in glass and black latex fluid, black paint, female face, woman body, hypperrealistic, bokeh, long exposure, close up portrait, fantasy concept art, epic light, clouds, god rays, heaven, art noveau, artistic sketch, dark mood, film still, swirly body painting ",
    "ultra realistic illustration of <concept> as a medieval old king, intricate, elegant, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, art by artgerm and greg rutkowski and alphonse mucha ",
    "Portrait of <concept>, highly detailed, marvel comics, dark, intricate, highly detailed, smooth, artstation, digital illustration by Ruan Jia and Mandy Jurgens and Artgerm and Wayne Barlowe and Greg Rutkowski and Zdislav Beksinski",
    "<concept>, the good kind king wearing a crown, ultra detailed fantasy, dndbeyond, bright, colourful, realistic, dnd character portrait, full body, pathfinder, pinterest, art by ralph horsley, dnd, rpg, lotr game design fanart by concept art, behance hd, artstation, deviantart, hdr render in unreal engine 5 ",
    "portrait of <concept> by Greg Rutkowski, an old jedi master, brown quiff hair, straight jaw, badass, wearing a flying jacket, he has about 70 years old, Star Wars Expanded Universe, highly detailed portrait, digital painting, artstation, concept art, smooth, sharp foccus ilustration, Artstation HQ",
    "portrait of <concept> by greg rutkowski, hiroyuki sanada as a ceo of weyland - yutani aliens franchise, he is about 5 0 years old, wearing futuristic office suit, highly detailed portrait, digital painting, artstation, concept art, smooth, sharp foccus ilustration, artstation hq ",
    "<concept> as a neolithic priest, male, cybernetically enhanced, sci fi character portrait by greg rutkowski, craig mullins ",
    "<concept>, Atlantis citizen, close-up portrait, poor, intricate, elegant, volumetric lighting, scenery, digital painting, highly detailed, artstation, sharp focus, illustration, concept art,ruan jia, steve mccurry",
    "Portrait of <concept> by Greg Rutkowski, symmetrical face, he is about 30 years old, messy long black hair, tired appearance, roman nose, he has become some sort of biomechanical transhuman god with eyes that glow electric blue, peaceful but sad expression, highly detailed portrait, digital painting, artstation, concept art, smooth, sharp foccus ilustration, Artstation HQ.",
    "eerie portrait of creepy pale old <concept> with fish like facial features and gills in his neck,  painted, fish man, trending on art station, love craftian, dark lighting",
    "A portrait of <concept> by Zdzisław Beksiński and Ilya Repin,In style of digital art illustration.Dark Fantasy.hyper detailed,smooth, sharp focus,trending on artstation,4k",
    "duncan trussell, shamanic poster lsd portrait of <concept>, intricate, elegant, highly detailed, centered, digital painting, artstation, concept art, smooth, sharp focus, illustration, artgerm, tomasz alen kopera, peter mohrbacher, donato giancola, joseph christian leyendecker, wlop, frank frazetta ",
    "<concept> as an aztec warrior, athletic, face paint, muscular, intricate, highly detailed, digital painting, artstation, concept art, sharp focus, illustration, art by greg rutkowski and alphonse mucha ",
    "digital painting of <concept> as a mayan warrior by filipe pagliuso and justin gerard, symmetric, fantasy, highly detailed, realistic, intricate, portrait, sharp focus, ",
    "digital painting of <concept> as itzamna, mayan ruler of heaven by filipe pagliuso and justin gerard, symmetric, fantasy, highly detailed, realistic, intricate, portrait, sharp focus, tarot card ",
    "formal portrait of <concept> as judah ben - hur, digital art by eugene de blaas, ross tran, and nasreddine dinet, vibrant color scheme, intricately detailed, in the style of romanticism, cinematic, artstation, greg rutkowski ",
    "digital painting of <concept> as incan lancer warrior, by filipe pagliuso and justin gerard, symmetric, fantasy, highly detailed, realistic, intricate, portrait, sharp focus, tarot card, face, handsome, peruvian ",
    "a concept art of <concept> as a warrior, light blue braids, chain mail, leather fur hide armor, a crown of bones of mammoths bones and white dragons bones, mammoth tusks draped over shoulders, holds an axe, concept art in style of Greg Rutkowski, painted by Frank Frazetta, John Singer Sargant",
    "digital _ painting _ of _ <concept>, puch mayan god of death _ by _ filipe _ pagliuso _ and _ justin _ gerard _ symmetric _ fantasy _ highly _ detailed _ realistic _ intricate _ port ",
    "<concept>, Aztec king, handsome, portrait, intricate, elegant, feathers, volumetric lighting, scenery, digital painting, highly detailed, artstation, sharp focus, illustration, concept art, ruan jia, steve mccurry",
    "<concept> as gilgamesh, mighty man, big smile, close up portrait, intricate, elegant, volumetric lighting, scenery, classical painting, in the style of rembrandt and tony sart and lucian freud and anato finnstark and randy vargas and diego gisbert llorens and johan grenier and ruan jia and steve mccurry, photorealistic lighting, sharp focus, illustration, concept art ",
    "photograph of a real - life <concept> octopus who is a hipster, wearing beanie and sunglasses",
    "photograph of a <concept> octopus who is a hipster, wearing beanie and sunglasses",
    "polaroid photo of a <concept> cthulhu, wearing a beanie and sunglasses",
    "polaroid photo of a <concept> cthulhu in a public pool at night",
]


female_prompts = [
    "highly detailed beautiful oil painting of <concept> angel, ink splash, sharp focus, dramatic, dynamic lighting, elegant, harmony, dark, masterpiece, by jenny saville, by lucian freud, by riccardo federici, by james jean, by craig mullins, by jeremy mann, by makoto shinkai, by krenz cushart, by greg rutkowski, by huang guangjian, by gil elvgren, illustration, ink draw, pen",
    "highly detailed beautiful oil painting of <concept>, ink splash, sharp focus, dramatic, dynamic lighting, elegant, harmony, dark, masterpiece, by jenny saville, by lucian freud, by riccardo federici, by james jean, by craig mullins, by jeremy mann, by makoto shinkai, by krenz cushart, by greg rutkowski, by huang guangjian",
    "highly detailed beautiful oil painting of naked <concept> woman, ink splash, sharp focus, dramatic, dynamic lighting, elegant, harmony, dark, masterpiece, by jenny saville, by lucian freud, by riccardo federici, by james jean, by craig mullins, by jeremy mann, by makoto shinkai, by krenz cushart, by greg rutkowski, by huang guangjian, by gil elvgren, illustration, ink draw, pen",
    "highly detailed beautiful oil painting of <concept> woman, ink splash, sharp focus, dramatic, dynamic lighting, elegant, harmony, dark, masterpiece, by jenny saville, by lucian freud, by riccardo federici, by james jean, by craig mullins, by jeremy mann, by makoto shinkai, by krenz cushart, by greg rutkowski, by huang guangjian, by gil elvgren, illustration, ink draw, pen",
    "<concept> as Visions of Hell by Karol Bak, Jean Deville, Gustav Klimt, and Vincent Van Gogh, nightmare portrait, infernal, visionary, otherworldly, fractal structures, ornate gilded medieval icon, third eye, hellfire, stygian, spirals, cosmic horror",
    "<concept> as Visions of Hell by Karol Bak, Jean Deville, Gustav Klimt, and Vincent Van Gogh, nightmare portrait, infernal, visionary, otherworldly, fractal structures, ornate gilded medieval icon, third eye, hellfire, spirals, horror",
    "<concept> as the Divine Chaos Engine by Karol Bak, Jean Deville, Gustav Klimt, and Vincent Van Gogh, celestial, visionary, sacred, fractal structures, ornate realistic gilded medieval icon, spirals, atmospheric",
    "<concept> as a totem aztek tribal deepdream intricate, elegant, sharp focus, illustration, highly detailed, digital painting, concept art, matte, art by WLOP and Artgerm and Greg Rutkowski and Alphonse Mucha, masterpiece",
    "perfectly-centered-Portrait of a sinister <concept> Goddess, intricate, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, Unreal Engine 5, 8K, art by artgerm and greg rutkowski and alphonse mucha",
    "<concept> human 3 d by pantokrator, beautiful sexy <concept> head made of mech mask rendered in unreal engine, nanotechnology, golden cyberntic vessels coming from core processor, contrast, painted by david burliuk | bernard buffet | carne griffiths | stanislaw lem ",
    "abstract expressionist mid shot portrait of a beautiful <concept>, body fully covered of very thick iridescent black impasto paint and iridescent black acrylic pour and iridescent black colour powder explosion and splashing iridescent black paint and dripping iridescent black paint and flying iridescent black paint chunks, eyes closed or not visible, expressing strong emotions, motion blur, hyperrealistic, intricate art photography, anatomically correct, realistic crisp textures, 1 6 k ",
    "blonde <concept> with tattoos and big earrings in a dark interior, beautiful pose, by jeremy mann",
    "high quality high detail painting of <concept> by jenny saville, hd, a skinny beautiful androgenous person, hair in wind, photorealistic lighting ",
    "<concept> as the knave of hearts, highly detailed, cinematic, 8 k, by megan duncanson, benjamin lacombe, adrian borda, stanley artgermm, tom bagshaw, craig mullins, carne griffiths, ayami kojima, beksinski, giger, trending on deviantart, hyper detailed, horror, full of colour ",
    "abstract expressionism oil painting of <concept> intertwined with a mutant biomorphic posthuman human head, spray paint texture, drips, impasto paint, 3 d graffiti texture, brushstrokes, abstract, highly detailed, hyperealistic fresh paint, harmonious, chaotic, colorfull, in the style of alphonse mucha ",
    "the <concept> goddess of mechanical pencils, painting by henry asencio ",
    "orgasm detailed and highly reliefed analogue mixed media collage of <concept> with canvas texture in style of conteporary art, punk art, hyperrealistic beautiful face, photorealistic, expressionism, masterpiece, perfect composition, spectacular quality, intricate oil details ",
    "highly detailed beautiful oil painting of <concept> woman, ink splash, sharp focus, dramatic, dynamic lighting, elegant, harmony, dark, masterpiece, by jenny saville, by lucian freud, by riccardo federici, by james jean, by craig mullins, by jeremy mann, by makoto shinkai, by krenz cushart, by greg rutkowski, by huang guangjian, by gil elvgren, illustration, ink draw, pen ",
    "artwork of <concept> by Dan Quintana",
    "betula pendula, beauty portrait of <concept>, fantasy digital art by moebius, greg rutkowski, denis sarazhin, mucha, highly detailed, artstation ",
    "beauty princess, <concept>, hyper detailed, insane details, intricate, elite, elegant, luxury, by ismail inceoglu dragan bibin hans thoma greg rutkowski alexandros pyromallis rene maritte illustrated, perfect face, fine details, realistic shaded, fine - face, pretty face ",
    "portrait of a cosmic <concept> goddess, suit made out of stars and galaxies and cosmic energy, intricate, headshot, highly detailed, digital painting, artstation, concept art, sharp focus, cinematic lighting, illustration, art by artgerm and greg rutkowski, alphonse mucha, cgsociety",
    "portrait of a cosmic <concept> goddess, suit made out of stars and galaxies and cosmic energy, intricate, headshot, highly detailed, digital painting, artstation, concept art, sharp focus, cinematic lighting, illustration, art by artgerm and greg rutkowski, alphonse mucha, cgsociety",
    "the crystal crown, <concept>, by Annie Swynnerton and  Nicholas Roerich and Diego Rivera, tattooed bioluminescent skin, elaborate costume, geometric ornament, symbolist, Luis Royo, rich color, dramatic cinematic lighting,  smooth, sharp focus, extremely detailed",
    "breathtaking detailed soft painting of a celestial <concept> being in stars and galaxy, gauze dress of fireflies and kabuto helm with big horns, rembrandt style, intricated ribbons of light, hall of ancient nature kings, in a nebulae galaxy in flames, elegant, highly detailed, artstation, concept art, matte, sharp focus, art by Anato Finnstark, Artgem and Greg Rutkowski",
    "portrait of the <concept> goddess of the sun, d & d, fantasy, intricate, elegant, highly detailed, digital painting, artstation, smooth, sharp focus, illustration, art by artgerm and greg rutkowski and alphonse mucha, technomancer astronaut with an epic cosmic background in the style of erak note, eddie mendoza, christophe young, craig mullins, evan lee, silvain sarrailh, dao trong le, kan liu, character design, trending on artstation ",
    "portrait of a cosmic <concept> god, body made out of stars and galaxies and cosmic energy, intricate, headshot, highly detailed, digital painting, artstation, concept art, sharp focus, cinematic lighting, illustration, art by artgerm and greg rutkowski, alphonse mucha, cgsociety",
    "portrait of a <concept> humanoid robot wearing a veil, mystic, mystical, robot body, wires, robotic, intricate, headshot, highly detailed, digital painting, artstation, concept art, sharp focus, cinematic lighting, digital painting, art by artgerm and greg rutkowski, alphonse mucha, cgsociety ",
    "a mayan quetzal <concept>, intricate , elegant , highly detailed, digital painting, artstation, concept art, matte, sharp focus, illustration, art by Artgerm and Greg Rutkowski and Alphonse Mucha",
    "a centered render of a single mystical tribal <concept> shaman adorned with feathers and gemstones and cables and synthesizer parts is surrounded by sacred geometry made from elven architecture and incense smoke, full body, gorgeous, perfect face, powerful, cinematic, beautifully lit, by artgerm, by karol bak, by viktoria gavrilenko, 3 d, trending on artstation, octane render, 8 k ",
    "Aztec sun goddess, <concept>, fantasy, bangles, explosion, dramatic, intricate, elegant, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, art by Hieronomous Bosch, octane render, art by Leesha Hannigan, Ross Tran, Thierry Doizon, Kai Carpenter, Ignacio Fernández Ríos",
    "a mystical render of a <concept> single alluring mystical tribal goddess adorned with feathers and gemstones and cables and synthesizer parts is surrounded by sacred geometry made from elven architecture, full body, gorgeous, perfect face, powerful, cinematic, beautifully lit, by artgerm, by karol bak, 3 d, trending on artstation, octane render, 8 k ",
    "<concept>, the divine queen, artstation hall of fame gallery, editors choice, #1 digital painting of all time, most beautiful image ever created, emotionally evocative, greatest art ever made, lifetime achievement magnum opus masterpiece, the most amazing breathtaking image with the deepest message ever painted, a thing of beauty beyond imagination or words",
    "a beautiful portrait of a <concept> water goddess by Greg Rutkowski and Raymond Swanland, Trending on Artstation, ultra realistic digital art",
    "ultra realistic illustration of a <concept>, a jade statue of sacred geometry, intricate, elegant, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, art by artgerm and greg rutkowski and alphonse mucha ",
    "highly detailed digital painting of a beautiful <concept> goddess by wlop, bright light emerging from her eyes, wearing venetian woman mask, sculpted in white opalescent marble, with lots of thin ornaments, disolving with a luminous background, curves and chaotic fractal art inlays, intricate, 8 k, white box, cinematic light, high aperture, background atmospheric effects ",
    "symmetry!! masks, machine parts embedded into <concept> face, intricate, elegant, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, art by artgerm and greg rutkowski and alphonse mucha, 8 k ",
    "beautiful japanese oil panting of <concept> in headdress, colorful brush strokes, rendered by octane, depth of field, ultra detailed, rococo, zen concept, powerful composition, trending on artstation, 8k",
    "russian war propaganda poster of <concept> by miguel covarrubias",
    "fallout 7 6 retro futurist illustration art of <concept> by butcher billy, sticker, colorful, illustration, highly detailed, simple, smooth and clean vector curves, no jagged lines, vector art, smooth andy warhol style",
    "Daft Punk logo of <concept> by mcbess, full colour print, Techno concert advert, DAFT PUNK CONCERT 24 Aout 2022",
    "portrait shot of <concept> alien, doom sf interstellar, intricate artwork masterpiece, ominous, matte painting movie poster, golden ratio, trending on cgsociety, intricate, epic, <concept>, trending on artstation, by h. r. giger and zdizslaw beksinski, ¨ francois marcela - froideval, highly detailed, vibrant, production cinematic character render, ultra high quality model",
]

random_prompts = [

]


# remove all empty prompts:
male_prompts = [f for f in male_prompts if (len(f) > 4 and "<concept>" in f)]
female_prompts = [f for f in female_prompts if (len(f) > 4 and "<concept>" in f)]