


text_inputs_v1 = [
    "japanese style shrine on top of a misty mountain overgrown, hyper realistic, lush gnarly plants, 8 k, denoised, by greg rutkowski, tom bagshaw, james gurney cinematic lighting",
    "deep in a velvet pine forest at dusk, foggy, ground view, matte painting, stunning detail, 4k, hd, clean, full of detail, sharp focus, rule of thirds by Makoto Shinkai, thomas kinkade, Karol Bak, trending on artstation",
    "Hogwarts train by Tyler Edlin and Jean Delville and John Aktinson Grimshaw and Robert Hubert, german romanticism style, oil on canvas, cinematic lighting, vibrant, hdr, concept art, water reflections",
    "portrait of a chinese cyberpunk machine, machine face, upper half portrait, decorated with chinese opera motifs, regal, asian, fine china, wuxia, traditional chinese art intricate intense elegant 京 剧 highly detailed digital painting artstation concept art smooth sharp focus illustration, art by artgerm and greg rutkowski alphonse mucha 8 k",
    "busy street view, blade runner, by greg rutkowski, highly detailed portrait, digital painting, artstation, concept art, smooth, sharp foccus ilustration, artstation hq",
    "3 d deer god of war close - up profile portrait with crown, ram skull. beautiful intricately detailed japanese crow kitsune mask and classical japanese kimono. betta fish, jellyfish, phoenix, bio luminescent, plasma, ice, water, wind, creature, artwork by tooth wu and wlop and beeple and greg rutkowski",
    "detailed character concept art portrait of an astronaut floating in an empty chamber, artstation, award - winning realistic sci - fi concept art by zdzisław beksinski and greg rutkowski, jim burns, a realism masterpiece, james gilleard, bruegel, alphonse mucha, and yoshitaka amano",
    " eerie, the rake walking to pov, very detailed, fantasy, dramatic, intricate, elegant, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, art by Gustave Dore, octane render",
    "portrait of a man with face tattoos, sci - fi, cyberpunk, blade runner, glowing lights, tech, biotech, techwear, intricate, elegant, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, art by artgerm and greg rutkowski and alphonse mucha",
    "a beautiful painting of a cyberpunk city on the sea by ivan aivazovsky and greg rutkowski and james gurney and frank lloyd and sung choi, in style of digital art illustration. hyper detailed, sharp focus, soft light. unreal engine 5 lumen. ray tracing. trending on artstation.",
    "tree of life, sacred geometry, illustration, high quality, details, intricate, atmosphere, highly detailed, cinematic, digital painting, deviantart, cinematic, concept art",
    "a macro photo of an ancient tree made from cables and bio - organic micro organisms and metal parts and led growing in a mystical setting, cinematic, beautifully lit, by tomasz alen kopera and peter mohrbacher and craig mullins, 3 d, trending on artstation, octane render, 8 k",
    "symmetry!! portrait of android fox woman in the style of god of war, machine parts embedded into face, intricate, elegant, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, art by artgerm and greg rutkowski and alphonse mucha, 8 k",
    "an old victorian city with rainy atmosphere and moody and cinematic lighting by alphonse mucha, simon stalenhag and darek zabrocki, cinematic and atmospheric, concept art, artstation, trending on artstation",
    "bodies entwined in a fight inside a vibrant, brutalist space ship, extremely intricate and detailed, by painted by francis bacon, adrian ghenie, and james jean. 8 k cinematic lighting, hyper realism",
    "mcqueen haute couture, oil paints building chaotic concept art, illustration, art station, the living sharp details, 4k, by Gustave",
    "mann, still life, dark leaves and elegant, hyper realistic, focus, emitting diodes, smoke, masterpiece, digital painting, porcelain cyberpunk robot ai a hyper detailed 3d",
    "bonsai trees, transcendent, giancola, joseph christian render, recursive shadow upon red details, nature lush another dimension, wayne stalenhag, thomas female cyborg concept art, lifelike",
    "chaotic structure a giant black, void room by Salvador Dalí, wide lens,kevlar,carbon post apocalyptic river bridge, directed by by greg rutkowski",
    "barlow, bao volumetric cinematic lighting, 8 k smooth puffy sculptural big leaves and pham, donato giancola, painting, aesthetic, smooth, bed above floor",
    "fine filigree foliage bathing in the upon itself, raytrace, detail, cinematic, intricate, cinematic resolution blade runner d render lee madgewick",
    "beautiful mannequin big leaves and coil of glass, facial hair petite nature lush floating bed of clouds post apocalyptic river bridge",
    "big leaves and style, volumetric lighting, nothingness, surreal concept big specular very detailed, alien room, details, roots, unreal engine, details, anatomical, facial woman in another",
    "style, volumetric and gold, cascading, multiverse a beautiful greg rutkowski, oil paint, art, lifelike, photorealistic, reclections, reflective",
    "flowing, cascading, glass museum, full of thousands detailed brain, mystical forest twisted style of Jonathan Zawada, light, ultrabright, depth detailed faces by",
    "a twisted trending on art shards of sharp 5, raytracing photorealistic, digital painting, irrational fear the existential dread f 3 black glass lenses floats through futuristic illustrated visionary",
    "beautiful mannequin big leaves and coil of glass, facial hair petite nature lush floating bed of clouds post apocalyptic river bridge",
    "biomechanical ivy composition, beautiful lighting, sharp + forest fractal veins, vegetal light, rim light, silver gold 8 k post - production",
    'a twisted coil of opaque and translucent glass casting a grim shadow upon itself, raytrace, backlit, unreal engine 5, vibrant colors',
    'a magnificent twisting coil of opaque and translucent glass casting a grim shadow upon itself, raytrace, backlit, unreal engine, vibrant colors',
    'a massive, translucent twisted coil of opaque and translucent glass casting a grim shadow upon itself, raytrace, backlit, unreal engine 5, vibrant colors',
    'an organic xenomorphic alien queen hive in a massive warehouse, twisting organic tendrils, haze, highly detailed hyper real retro interior high ceilings, retro futuristic, volumetric interior lighting, artstation, unreal engine render 8 k, greg rutkowski',
    'a twisted tree growing in an abandoned brutalist bunker, in the round, skylight with light shining down, snow falling through skylight, photorealistic',
    'magnificent tree of life growing in an abandoned brutalist bunker, in the round, skylight with light shining down, snow falling through skylight, photorealistic',
    "you won't ever catch my love detailed and highly reliefed oil painting and analogue collage with canvas texture in style of conteporary art, photorealistic, surrealism, expressionism, masterpiece, balanced composition, calm vivid colors, grim atmosphere, spectacular quality, trending on artstation, intricate oil details",
    "only with blue ney motogrosso in love with a red demon, too many mouths and faces in all directions in hoc signo vinces forest in the style of leonora carrington gottfried helnwein intricate composition, blue light by rembrandt insanely quality highly detailed masterpiece red light",
    "complex 3d render of a beautiful porcelain cyber robot ai face, blue and gold, fractal veins, vegetal dragon cyborg, 1 5 0 mm, beautiful natural soft light, rim light, silver gold details, roots, fine lace, mandelbot fractal, anatomical, glass, facial muscles, elegant, ultra detailed, metallic armor, octane render",
    "intricate hyper detailed ultra sharp 3d rendering of a beautiful afro porcelain aztec warrior medium portrait shot, 1 5 0 mm, global illumination, radiant light, ultrabright, depth of field, biomechanical ivy cyborg, cyberpunk, fractal, art nouveau, black eyes, large monochromatic earthy red leaves and stems, roots, fine ivory lace, white large pore fungi, feathers, alexander mcqueen haute couture, face tattoos, intricate details, mesh wire, anatomical, flesh ornate, facial muscles, cable wires, elegant, hyper realistic, ultra detailed, octane render, h. r. giger style, volumetric cinematic lighting, 8k post - production",
    "complex 3d full of light render hyper detailed ultra sharp of a beautiful porcelain profile woman face, biomechanical cyborg, 1 5 0 mm lens, global illumination, rim light, beautiful eyes, plump lips, magnolia big leaves achromatic and stems, sinuous roots, fine filigree foliage lace, silver white gold red details, alexander mcqueen high fashion haute couture, art nouveau fashion embroidered, intricate details, mesh wire, hyper realistic, ultra detailed, mandelbrot fractal, anatomical, facial muscles, cable wires, white background, microchip, cyborg with a visible detailed brain, grey matter and neurons, elegant, octane render, h. r. giger style, 8k post - production",
    "complex 3d render ultra detailed of a beautiful porcelain profile deadmau5 helmet, biomechanical cyborg, analog, 150 mm lens, beautiful natural soft rim light, big leaves and stems, roots, fine foliage lace, Dichroistic, blue, red details, massai warrior, Alexander Mcqueen high fashion haute couture, pearl earring, art nouveau fashion embroidered, steampunk, intricate details, mesh wire, mandelbrot fractal, anatomical, facial muscles, cable wires, microchip, elegant, hyper realistic, ultra detailed, octane render, H.R. Giger style, volumetric lighting, 8k post-production",
    "complex 3d render of a beautiful symmetric porcelain cyberpunk robot ai face, blue and gold, fractal veins, vegetal dragon cyborg, 1 5 0 mm, beautiful natural soft light, rim light, silver gold details, roots, fine lace, mandelbot fractal, anatomical, glass, facial muscles, elegant, ultra detailed, metallic armor, octane render",
    "a cybernetic symbiosis of a single engineer astronaut mech-organic eva suit made of pearlescent wearing knitted shiny ceramic multi colored yarn thread infected with diamond 3d fractal lace iridescent bubble 3d skin dotted covered with orb stalks of insectoid compound eye camera lenses floats through the living room, film still from the movie directed by Denis Villeneuve with art direction by Salvador Dalí, wide lens,kevlar,carbon fiber,ceramics,gaseous materials",
    "complex 3d render, hyper detailed, ultrasharp, fascinating biomechanical female cyborg with a porcelain translucent profile face, analog, 1 5 0 mm lens, beautiful natural soft rim light, big colorful autumn leaves and stems, hexagonal mesh fine wire, neural network, sinuous fine roots, fine filigree foliage lace, luxurious, elegant, alexander mcqueen high fashion haute couture, earring, art nouveau fashion embroidered, steampunk, intricate details, mandelbrot fractal, white background, pastel yellow light soft orange details, anatomical, facial muscles, cable wires, translucent microchip, hyper realistic, ultra detailed, octane render, h. r. giger style, volumetric lighting, 8k post - production",
    "complex 3d render, hyper detailed, ultrasharp, fascinating biomechanical female cyborg with a porcelain translucent profile face, analog, 1 5 0 mm lens, beautiful natural soft rim light, big colorful autumn leaves foliage and stems, romantic, atmospheric, hexagonal mesh fine wire, neural network, sinuous fine roots, fine filigree foliage lace, luxurious, elegant, alexander mcqueen high fashion haute couture, earring, art nouveau fashion embroidered, steampunk, intricate details, mandelbrot fractal, white background, pastel yellow light soft orange details, anatomical, facial muscles, cable wires, translucent microchip, hyper realistic, ultra detailed, octane render, h. r. giger style, volumetric lighting, 8k post - production",
    "complex 3d render ultra detailed of a beautiful porcelain profile doja cat face, biomechanical cyborg, analog, 150 mm lens, beautiful natural soft rim light, big leaves and stems, roots, fine foliage lace, silver dechroic details, massai warrior, Alexander Mcqueen high fashion haute couture, pearl earring, art nouveau fashion embroidered, steampunk, intricate details, mesh wire, mandelbrot fractal, anatomical, facial muscles, cable wires, microchip, elegant, hyper realistic, ultra detailed, octane render, H.R. Giger style, volumetric lighting, 8k post-production",
    "biocomputer organs inside a bioneural antique lace in a biomechanical cave forest with biocomputer flowers, epic environment, matte painting, diffused lighting, highly detailed cinematic, epic atmosphere, diffused lighting, highly detailed digital art, trending on artstation, depth of field, wide angle",
    "a cybernetic symbiosis of a single engineer astronaut mech-organic eva suit made of pearlescent wearing knitted shiny ceramic multi colored yarn thread infected with diamond 3d fractal lace iridescent bubble 3d skin dotted covered with orb stalks of insectoid compound eye camera lenses floats through the living room, film still from the movie directed by Denis Villeneuve with art direction by Salvador Dalí, wide lens,kevlar,carbon fiber,ceramics,gaseous materials",
    "engineer prometheus face by Artgerm, xenomorph alien, highly detailed, symmetrical long head, smooth marble surfaces, detailed ink illustration, raiden metal gear, cinematic smooth stone, deep aesthetic, concept art, post process, 4k, carved marble texture and silk cloth, latex skin, highly ornate intricate details, prometheus, evil, moody lighting, hr geiger, hayao miyazaki, indsutrial Steampunk",
    "glitchy cubes, magic halo, broken soul, deep sickness oil paint, surrealist highly detailed at, ethereal, trending on art station, emotional surrealism oil painting, tears, crying, glitching squares, very very very very very beautiful and painful, aged damaged on edges, hell fire pain",
    "the black lioness made of tar, bathing in the bathtub filled with tar, dripping tar, drooling goo, sticky black goo, photography, dslr, reflections, black goo, rim lighting, modern bathroom, hyper realistic, 8k resolution, unreal engine 5, raytracing",
    "photograph of retro interior of glass museum, full of thousands of glass televisions from different places of our universe, sharp details, back light contrast, dramatic dark atmosphere, bright vivid colours, reclections, reflective ground, speculars, refractions, light disperions, painted by Gustave Dore, George Inness, Lee Madgwick",
    "black decadent hood, gold intricately detailed ornate metal mask, ornate background, portrait, realism, cinematic lighting, specular lighting, 8 k, artstation, octane render, peter mohrbacher, alfonso mucha, zdzislaw beksinski",
    "flume and former cover art silk fabric skin big specular transparent glass shards of sharp glass cutting through skin skin peels like fabric dress skin future bass girl un wrapped statue bust curls of hair petite nature lush body photography model body art futuristic branches material style of Jonathan Zawada, Thisset colours",
    "Wide view of a room interior of strange hardware geek from far future, full of various electronic hardware components, devices and instruments, incredible sharp detail, back light contrast, dramatic dark atmosphere, bright vivid colours, reclections, metal speculars, rendered in Unreal Engine, 4k",
    "flume and former cover art silk fabric skin big specular transparent glass shards of sharp glass cutting through dress skin future bass girl un wrapped statue bust curls of hair petite nature lush body photography model body art futuristic branches material style of Jonathan Zawada, Thisset colours",
    "self-hatred as a candid way to survive, soft memories, ocean specular, all along the stars, astrophotography, odissey, gritty feeling, imagining a blissful fate, conflicted emotions, anger, sadness, facial expression, emotive portrait, by Francis Bacon, by Beksinski, contemporary masterpiece, neo-expressionism, war photography, photojournalism, antithesis, dialogue, chaotic revenge, loneliness, soul, melancholy",
    "photograph of retro interier of glass museum, full of thousands of glass televisions from different places of our universe, incredible sharp details, back light contrast, dramatic dark atmosphere, bright vivid colours, reclections, reflective ground, speculars, refractions, light disperions, sharp details, 4k, by Gustave Dore, George Inness",
    "photograph of retro interier of the museum of dreams, full of thousands of glass televisions from different places of our universe, incredible sharp details, back light contrast, dramatic dark atmosphere, bright vivid colours, reclections, reflective ground, speculars, refractions, light disperions, sharp details, 4k, by Gustave Dore, George Inness",
    "a beautiful glitched painting by robert proch of people in front of a painting in a museum gallery, metal rust and plaster materials, pixel sorting, color bleeding, brushstrokes by jeremy mann, still life, dark colors",
    "surreal baroque portrait of ribbed white alien god covered with spinal antlers, on white exoplanet, iredescent soft glow bloom effect, dream - like, baroque portrait painting, perfect composition, beautiful detailed intricate detailed octane render, artstation, 8 k, photorealistic, volumetric cinematic light, chiaroscuro, masterpiece, raphael, caravaggio, beksinski, giger",
    "award winning photo of ritualistic deformed irish celtic albino crow draped in shiny gold and oil, puking blood, red eyes wide open, rotten flesh, dead bluebirds, evil cult, irish mysticism, vivid colors, weird and disturbing, symmetrical face, grape hyacinth, blue delphinium, studio lighting, wide shot art by sally mann & arnold newman",
    "hyper realistic painting of a macaw, gold ornaments, flowing fabric, intrincate detail, detailed faces by wayne barlowe, gustav moreau, goward, gaston bussiere and roberto ferri, santiago caruso, and austin osman spare, occult art, bouguereau, alphonse mucha, saturno butto",
    "beautiful mannequin sculpted out of black glass by billelis + lit with geometric neon dripping gold + forest in background facing a doorway opening with neon pink geometric fractal light + flowering bonsai trees, transcendent, clean linework, dramatic, finely detailed, award winning, 4 k, trending on artstation, photorealistic, volumetric lighting, octane render",
    "complex 3d render of a beautiful porcelain cyber robot ai face, blue and gold, fractal veins, vegetal dragon cyborg, 1 5 0 mm, beautiful natural soft light, rim light, silver gold details, roots, fine lace, mandelbot fractal, anatomical, glass, facial muscles, elegant, ultra detailed, metallic armor, octane render",
    "snail vs knight, wide angle, italian masterpiece, Ashford Black Marble, sculpture, baroque,  draped with red Hibiscus and vines and spines, marble and gold, drapes, dead fruits, Obsidian, portrait, rabbit, chariot, snails vs knight, render, artstation, ultra detailed",
    "the immortal neuron, alien room, intricate scifi, highly detailed, singularity, prometheus, cybernetic, energy spheres, masterpiece, digital painting, artstation, cgsociety, concept art, highly detailed, art by roberto digiglio and furio tedeschi and filippo ubertino",
    "the immortal neuron, alien room, intricate scifi, highly detailed, singularity, prometheus, cybernetic, energy spheres, masterpiece, digital painting, artstation, cgsociety, concept art, highly detailed",
    "hyperrealism, detailed textures, photorealistic 3d render, an massive scale cave with a mini futuristic city inside, a central perfect large glass sphere with lightening and storm clouds inside,, in the style of sahm, in the style of escher, ultra realistic, ultra high pixel detail, cinematic, intricate, cinematic light, concept art, illustration, art station, unreal engine 8k",
    "steampunk armillary sphere, intricate, highly detailed, complex 3d render by simon stalenhag, thomas kinkade, greg rutkowski, craig mullins, hyper realistic, ray tracing, unreal engine, blender, sharp focus, luminous, glass, ray of lights, fractal crystal",
    "the immortal being dissolving into a new universe and then folding itself into a sphere that breaks reality, in the style of wlop, epic, fantasy, cgsociety, hyper detailed, unreal engine, sharp focus, ray tracing",
    "artwork about a sad sphere - headed character, by viktor vasnetsov. atmospheric ambiance. depth of field and tridimensional perspective. foggy",
    "portrait of a futuristic geisha cyborg embryo, kintsugi, modern fine art, fractal, intricate, elegant, highly detailed, digital photography, subsurface scandering, by jheronimus bosch and greg rutkowski",
    "epic naval battle during ocean storm, lightnight storm, pirate galleons. trending on artstation, by joseph mallord william turner, luis royo, konstantin razumov, cinematic lighting, fractal flame, highly detailed",
    "futuristic illustrated visionary robot mayan warriors, bladerunner 2049, complex armor, oracle witch, robotic cnc surgical arms and cybernetic symbiosis, machine ai singularity, infinity eyes, hybrid machine, serpitine laboratory, art by artgerm and chris dyer, ben ridgeway, alex grey, global illumination, octane render, ancient architectural, f 3 2",
    "post apocalyptic river bridge, building, boats, avenue, urban architecture, americana architecture, concrete architecture, paved roads, by thomas kinkade trending on artstation, photorealistic, wild vegetation, hyper detailed, hyper realistic neon cyberpunk blade runner mist",
    "gloomy ruined server room in datacenter robot automata rusty steel robot knight colossus welder pacing fixing mono eyed, sharp focus, emitting diodes, smoke, artillery, sparks, racks, system unit, motherboard, by pascal blanche rutkowski repin artstation hyperrealism painting concept art of detailed character design matte painting, 4k resolution blade runner",
    'scenic dystopian portal to a different universe environment, intricate, elegant, highly detailed, centered, digital painting, artstation, concept art, smooth, sharp focus, illustration, artgerm, tomasz alen kopera, peter mohrbacher, donato giancola, joseph christian leyendecker, wlop, boris vallejo',
    'fluid polygonal masses of golden oil paints building chaotic structure of hyper beautiful young man in sexual bliss and arousal, wayne barlow, bao pham, donato giancola, larry elmore, masterpiece, trending on artstation, featured on pixiv, cinematic composition, beautiful lighting, sharp',
    'fluid polygonal masses of golden oil paints building chaotic structure of hyper beautiful young man in arousal, shrouded and cloaked, wayne barlow, bao pham, donato giancola, larry elmore, masterpiece, trending on artstation, featured on pixiv, cinematic composition, beautiful lighting, sharp',
    'fluid polygonal masses of golden oil paints building chaotic structure of hyper beautiful young man in other dimension, wayne barlow, bao pham, donato giancola, larry elmore, masterpiece, trending on artstation, featured on pixiv, cinematic composition, beautiful lighting, sharp, details, hyper - detailed, hdr, 4k, 8k',
    'fluid polygonal masses of golden oil paints building chaotic structure of a beautiful young woman in another dimension, wayne barlow, bao pham, donato giancola, larry elmore, masterpiece, trending on artstation, featured on pixiv, cinematic composition, beautiful lighting, sharp, details, hyper detailed, 4k, 8k',
    'dreamlike photo of floating bed above floor in a giant room with windows opening to eternity by andrzej sykut by lee madgewick, photorealistic, octane render, recursive flowing, cascading, multiverse labyrinthine, optical illusion, impossible angles',
    'dreamlike photo of floating bed of clouds above floor in a giant red marble room with windows opening to eternity by andrzej sykut by lee madgewick, photorealistic, octane render, recursive flowing, cascading, multiverse labyrinthine, optical illusion, impossible angles',
    'dreamlike photo of floating bed above floor in a giant black, void room with windows opening to eternity by andrzej sykut by lee madgewick, photorealistic, octane render, recursive flowing, cascading, multiverse labyrinthine, optical illusion, impossible angles',
    'a hyper - detailed 3d render of our irrational fear of eternal nothingness, surrealism surreal concept art, lifelike, photorealistic, digital painting, aesthetic, smooth, sharp focus, artstation hd, by greg rutkowski, bruce pennington, valentina remenar and asher duran',
    'a hyper - detailed 3d render of our irrational fear of eternal nothingness, surrealism surreal concept art, lifelike, photorealistic, digital painting, aesthetic, smooth, sharp focus, artstation hd, by greg rutkowski, bruce pennington, valentina remenar and asher duran',
    'a hyper detailed 3d render of our irrational fear of eternal nothingness, surreal concept art, lifelike, photorealistic, digital painting, aesthetic, smooth, sharp focus, artstation hd, by greg rutkowski, bruce pennington, valentina remenar and asher duran',
    'the existential dread you feel as all of the worlds hope is sucked out of an eternal void, filling lost souls with the forgotten memories of their past, art by yiosgs ghdsjkhg, high detailed, super high resolution, realistic, concept art, artistic, octane render, masterpiece fine details',
    'a huge ultra detailed flock of many smooth puffy sculptural whirling elegant clouds with filigreed twisting turning gemstone crystal sculptures, art nouveau jungle environment, soothing, crepuscular, award winning art, epic dreamlike fantasy landscape, ultra realistic',
    'scary fairy tale mystical forest twisted creepy trees magical forest landscape artwork trees near the path amazing nature, surreal, dreamlike, lucid dream, very detailed, perfect lighting, perfect composition, 4 k, artgerm, derek zabrocki, greg rutkowski',
    "dystopian surreal painting aliens in shrouds praying to a single eerie head statue surrounded by uneven buildings, artstyle by zdzisław beksinski, cgsociety, hyper detailed, unreal engine, sharp focus, ray tracing",
    "Interior of the library in Elrond's Chamber at Rivendell, trees growing inwards, evening, detailed matte painting, cinematic, Alan Lee, Artstation",
    "a beautiful giant tree growing in the middle of an ancient vast Victorian library indoors. a stone arch in the library tree. Darksouls concept art, ultra-realistic, 4K, featured on artstation",
    "a beautiful giant tree growing in the middle of an ancient Victorian library indoors. a door is embedded in the tree. fantasy digital art, fantasy style art, fantasy hearthstone art style, fantasy game art by greg rutkowski, darksouls concept art",
    "a giant creature in a lush trunda vegetation, snow snow : : by michal karcz, daniel merriam, victo ngai and guillermo del toro : : ornate, dynamic, particulate, intricate, elegant, highly detailed, centered, artstation, smooth, sharp focus, octane render, 3 d ",
    "( ( ( ( pokemon ) ) ) ) creature creature in a lush alaska vegetation, backlit, warm tones, bioluminescent bioluminescent translucent translucent : : by michal karcz, daniel merriam, victo ngai and guillermo del toro : : ornate, dynamic, particulate, intricate, elegant, highly detailed, centered, artstation, smooth, sharp focus, octane render, 3 d ",
    "creature in a lush trunda vegetation, snow snow :: by Michal Karcz, Daniel Merriam, Victo Ngai and Guillermo del toro :: ornate, dynamic, particulate, intricate, elegant, highly detailed, centered, artstation, smooth, sharp focus, octane render, 3d",
    "a giant creature in a lush trunda vegetation, snow snow : : by michal karcz, daniel merriam, victo ngai and guillermo del toro : : ornate, dynamic, particulate, intricate, elegant, highly detailed, centered, artstation, smooth, sharp focus, octane render, 3 d ",
    "highly detailed creepy forest humanoide creature, stephen bliss, unreal engine, fantasy art by greg rutkowski, loish, rhads, ferdinand knab, makoto shinkai and lois van baarle, ilya kuvshinov, rossdraws, tom bagshaw, global illumination, radiant light, detailed and intricate environment",
    "a giant creature in a lush jungle vegetation, by Michal Karcz, Daniel Merriam, Victo Ngai and Guillermo del toro, ornate, dynamic, particulate, intricate, elegant, highly detailed, centered, artstation, smooth, sharp focus, octane render, 3d",
    "a giant creature in a dune filled desert landscape, by Michal Karcz, Daniel Merriam, Victo Ngai and Guillermo del toro, ornate, dynamic, particulate, intricate, elegant, highly detailed, centered, artstation, smooth, sharp focus, octane render, 3d",
    "creature / machine in a lush tropical vegetation, snow, fractal : : by michal karcz, daniel merriam, victo ngai and guillermo del toro : : ornate, dynamic, particulate, intricate, elegant, highly detailed, centered, artstation, smooth, sharp focus, octane render, 3 d",
    "closeup portrait shot of a meditation in cosmic void in a scenic dystopian environment, intricate, elegant, highly detailed, centered, digital painting, artstation, concept art, smooth, sharp focus, illustration, artgerm, tomasz alen kopera, peter mohrbacher, donato giancola, joseph christian leyendecker, wlop, boris vallejo",
    "oil painting of rage abstract surrealist forms by yvonne mcgillivray by mandy jurgens by michael divine, powerful eyes glowing highly detailed painting of l sadness alone, spiritual abstract forms, symmetrical, trending on art station, abstract emotional rage expression, very beautiful, fantasy digital art, highly detailed patterned visionary art, magic symbols, by michael divine, cosmic nebula",
    "closeup portrait shot of a cosmic meditation in a scenic dystopian environment, intricate, elegant, highly detailed, centered, digital painting, artstation, concept art, smooth, sharp focus, illustration, artgerm, tomasz alen kopera, peter mohrbacher, donato giancola, joseph christian leyendecker, wlop, boris vallejo",
    "a spooky, gothic treehouse by thomas kinkade, evening light, fantasy, artstation, illustration",
    "breathtakingly beautiful ultrawide angle colour masterpiece of a creepy family by roger dean and greg hildebrandt and kilian eng and jean giraud and beeple, forest clearing, lake, reflection, symmetry, secret overgrown temple, mysterious person looking over shoulder, incredible sense of depth and perspective and clarity, arch, weird abstract, 8 k",
    "a closeup portrait of a woman wrapped in plastic, standing next to a giant huge levitating copper orb, in a foggy pond, golden hour, color photograph, by vincent desiderio, canon eos c 3 0 0, ƒ 1. 8, 3 5 mm, 8 k",
    "The Futuristic Faberge Egg City by Greg Rutkowski, astronauts, magical glow, inspired by Stephan Martiniere and O'Neill Cylinder, fantasy, realistic, ultra detailed, atmospheric, cinematic lighting, movie concept art, hyper detailed, octane render, 8k",
    "galactic o'neill cylinder, cgsociety, hyper detailed concept art, 8k, unreal engine, trending on artstation",
    "magic stone portal in the forest, cinematic lighting, dramatic, octane render, long lens, shallow depth of field, bokeh, anamorphic lens flare, 8k, hyper detailed",
    "friendly dryad tree creature, in a forest, golden hour, professional photography, mild depth of field, cinematic lighting, 8 k ",
    "life in a bottle, mini ecosystem inside bottle, splashes, wet, forest, eerie and fantastic, digital art, 8 k, on a wooden table, unique source of light",
    "Beautiful artwork garden of the future, overgrown with fir trees and plants. Nice colour scheme, warm colour. Beautiful artistic digital artwork by artist Lurid. (2022), Gediminas Pranckevicius",
    "a hyper - detailed 3 d render of nature witnessing itself through all life, surrealism!!!!! surreal concept art, lifelike, photorealistic, digital painting, aesthetic, smooth, sharp focus, artstation hd, by greg rutkowski, bruce pennington, valentina remenar and asher duran",
    "photo of a crystal mirror that is a portal to another magical world. Forest in the background. Fantasy magic style. Highly detailed 8k. Intricate. Award winning photography.",
    "an ornate glass and cast iron terrarium containing ancient standing stones in a forest clearing, by paulette tavormina and michael whelan, old terrarium with intricate geometric decoration in a dark dusty parlor, hyper realistic, extremely detailed, dramatic lighting, octane render, featured on artstation",
    "a miniature tabletop forest glowing under an ornate glass dome, by paulette tavormina and michael whelan and donato giancola, inside a dusty abandoned laboratory, hyper realistic, extremely detailed, dramatic lighting, victorian, unreal engine, featured on artstation",
    "a miniature tabletop forest glowing under an ornate glass dome, by paulette tavormina and michael whelan and donato giancola, on a sumptuous tablecloth, hyper realistic, extremely detailed, dramatic lighting, victorian, unreal engine, featured on artstation",
    "the planets revolving around the giant Tree of Life, beautiful, oil on canvas, intricate, 8k highly professionally detailed, cinematic, CGsociety",
    "a beautiful and highly detailed matte painting of a carved elven portal a land with no gravity, celtic knots, epic scale, insanely complex, hyperdetailed, sharp focus, hyperrealism, artstation, cgsociety, 8 k, by caspar friedrich, albert bierstadt, james gurney, brian froud",
    "a beautiful giant tree growing in the middle of an ancient Victorian library indoors. a child reading a book under a library tree. by Albert Bierstadt, ultra-realistic, 4K, featured on artstation",
    "a beautiful giant tree growing in the middle of an mysterious   Victorian library indoors. a door is embedded in the tree. godray on plants,  fantasy digital art, fantasy style art, fantasy hearthstone art style, fantasy game art by greg rutkowski, darksouls concept art",
    "surreal glimpse into other universe, floating island in the sky, summer morning, very coherent and colorful high contrast, art by!!!! gediminas pranckevicius!!!!, geof darrow, dark shadows, hard lighting ",
    "chaotic structure a giant black, void room by Salvador Dal\u00ed, wide lens,kevlar,carbon post apocalyptic river bridge, directed by by greg rutkowski",
    "elegant, highly detailed, mystical forest twisted proch of people above floor in a giant",
    "a great, twisted tree growing in an abandoned brutalist bunker, in the round, skylight with light shining down, snow falling through skylight, photorealistic",
    "cinematic, the goddess of poppy flowers, sunny autumn, futuristic hospital, sci - fi, digital art, frombastien lecouffe-deharme and bruce pennington, extremely moody lighting stunning, wayne barlow, finely detailed",
    "magnificent tree of life growing in an abandoned brutalist bunker, bathing in sunlight, in the round, skylight with light shining down, photorealistic, cinematic composition, beautiful lighting, sharp, details, hyper detailed, 4k, 8k",
    "big leaves and style, volumetric lighting, nothingness, surreal concept big specular very detailed, alien room, details, roots, unreal engine, details, anatomical, facial woman in another",
    "fine filigree foliage bathing in the upon itself, raytrace, detail, cinematic, intricate, cinematic resolution blade runner d render lee madgewick",
    "Digital art, Oil on canvas, jean-Michel Basquiat style of TUPAC SHAKUR!!!!!, abstract jean-Michel Basquiat!!!!!!!! oil painting with thick paint strokes!!!!!!!!, oil on canvas, aesthetic, y2k!!!!!!, intricately!!!!!!!! detailed artwork!!!!!!!, trending on artstation, in the style of jean-Michel Basquiat!!!!!!!!!!!!, by jean-Michel Basquiat!!!!!!!!!!!, in the style of jean-Michel Basquiat!!!!!!!!!!!, in the style of jean-Michel Basquiat!!!!!!!!!!!, in the style of jean-Michel Basquiat!!!!!!!!!!!, in the style of jean-Michel Basquiat!!!!!!!!!!!, in the style of jean-Michel Basquiat!!!!!!!!!!!, david choe",
    "a man being overcome by love conciseness, psychedelic dripping colors, detailed painting by painting by pablo amaringo",
    "face shredded like paper as skin peeling, dark, surreal, illustration, by ally burke",
    "a cyberpunk portrait of a lewis hamilton by jean - michel basquiat, by hayao miyazaki by artgerm, highly detailed, sacred geometry, mathematics, snake, geometry, cyberpunk, vibrant, water",
    "a cyberpunk portrait of a samurai warrior by jean - michel basquiat, by hayao miyazaki by artgerm, highly detailed, sacred geometry, mathematics, snake, geometry, cyberpunk, vibrant, water",
    "naturepunk deity of retrofuture dream logic creativity, beautiful detailed realistic cinematic and with cyberpunk super computer ai that looks like kodak black, concept fashion revolutionary war propaganda portrait, hi - fructose art magazine, by anton fadeev and paul lehr and david heskin and josan gonzalez, 8 k",
    "a cyberpunk portrait of a famous actor by jean - michel basquiat, by hayao miyazaki by artgerm, highly detailed, sacred geometry, mathematics, snake, geometry, cyberpunk, vibrant, water ",
    "portrait of a bolivian woman ( 3 5 ) from bolivia in 2 0 2 1, an oil painting by ross tran and thomas kincade",
    "a portrait of a female shaman, upper half portrait, decorated with russian motifs, russian shaman, siberia, traditional russia, intricate, elegant, highly detailed, symmetry, headpiece, digital painting, artstation concept art smooth sharp focus, illustration, art by artgerm and greg rutkowski alphonse mucha 8 k",
    "portrait of catriona balfe as a long - neck kayan woman, hyper detailed ultra sharp trending on artstation, warpaint aesthetic, colorful, psychedelic, ornate, intricate, digital painting, concept art, smooth, sharp focus, illustration, art by artgerm and greg rutkowski and h. r. giger, 8 k",
    "a cubism portrait of a woman with very long legs vibrant color scheme, highly detailed, in the style of romanticism, cinematic, artstation, moebius, greg rutkowski",
    "hyper detailed ultra sharp 3 d render like a oil painting aztec serpent warrior princess, fractal plane, deep voyage, parallel existence, earthwave, colorful, neon, ornate, intricate, digital painting, concept art, smooth, sharp focus, illustration, art by artgerm and greg rutkowski and h. r. giger, 8 k",
    "portrait of a stunningly beautiful alien tribal female, depth of field, zeiss lens, detailed, symmetrical, centered, fashion photoshoot, by Annie Leibovitz and Steve McCurry, David Lazar, Jimmy Nelsson, Breathtaking, 8k resolution, extremely detailed, beautiful, establishing shot, artistic, hyperrealistic, beautiful face, octane render",
    "portrait of a stunningly beautiful asian tribal female, minimal red facepaint over the eyes in a stripe, depth of field, zeiss lens, detailed, symmetrical, centered, fashion photoshoot, by Annie Leibovitz and Steve McCurry, David Lazar, Jimmy Nelsson, Breathtaking, 8k resolution, extremely detailed, beautiful, establishing shot, artistic, hyperrealistic, beautiful face, octane render",
    "a beautiful surreal illustration of an amazon rainforest shaman, highly detailed, liquid oilpaint, doug chiang, gustave dore, leonardo da vinci, trending on artstation, industry, lucid and intricate, rectilinear, digital art, octane, redshift, vray, 8 k, 6 4 megapixels, zbrush central, behance hd, hypermaximalist, well rendered",
    "a hyperrealistic fine art portrait photo of a mechanical industrial alloy cybernetic human with psychedelic colorful body paint, by brad kunkle, maarten schröder and tom bagshaw, smooth shapes and lines, vignette, 35mm lens, golden ratio composition, studio photography, closed eyes, very detailed, artstation, 8K, highly coherent",
    "highly detailed surreal vfx portrait of a metallic chromatic geometric tribal woman, behance, stephen bliss, unreal engine, greg rutkowski, loish, rhads, beeple, makoto shinkai and lois van baarle, ilya kuvshinov, rossdraws, tom bagshaw, alphonse mucha, global illumination, detailed and intricate environment",
    "mosaic portrait of a beautiful cute girl with robot ears by Saimir Strati, 4k, intricate details, shining vibrant colors in the background",
    "halfturn portrait of a big crystal face made of crystals half - turn, bottom view, ominous, intricate, studio, art by anthony macbain + greg rutkowski + alphonse mucha, concept art, 4 k, sharp focus",
    "art deco patterns, blue and gold, 8 k, close - up portrait, powerfull, intricate, elegant, volumetric lighting, scenery, digital painting, highly detailed, artstation, sharp focus, illustration, concept art, ruan jia, steve mccurry, beksinski",
    "the most original and beautiful profile picture on discord, symetrical, 4 k, beautiful gorgeous digital art, trending on artstation",
    "a human made of moss and flowers, full body view, beautiful high quality realistic fantasy art, trending on artstation by artgerm and greg rutkowski and alphonse mucha",
    "portrait of the afro - american queen of the underworld, surrounded by flowers by karol bak, james jean, tom bagshaw, rococo, sharp focus, trending on artstation, cinematic lighting, hyper realism, octane render, 8 k, hyper detailed",
    "muscular female druid swathed in flowers, perfect face, thin antlers, green halter top, ginger hair, abs, cinematic, freckles, stunning, athletic, strong, agile, highly detailed, psychedelic, digital painting, artstation, smooth, hard focus, illustration, art by jessica rossier and and brian froud",
    "a sculpture made of vine and colorful flowers, bust, single portrait, queen, future, epic, harper's bazaar, vogue, magazine, insanely detailed and intricate, concept art, ornate, luxury, elite, elegant, trending on artstation, by Ruan Jia, Kenneth Willardt, Ross Tran, WLOP, Andrei Riabovitchev.",
    "portrait of the african queen of the underworld, surrounded by flowers by karol bak, james jean, tom bagshaw, rococo, sharp focus, trending on artstation, cinematic lighting, hyper realism, octane render, 8 k, hyper detailed.",
    "portrait of the young goddess of the neon cyber descent, unusual beauty, purple flowers and plants and fungi, emotionally evoking symbolic metaphors, head in focus, fantasy, ornamental, intricate, elegant, sensual, highly detailed digital painting, artstation, concept art, painterly, golden ratio, sharp focus, illustration, art by tomasz alen kopera and zdzisław beksinski and alphonse mucha",
    "an epic landscape with a huge woman head trapped in stone, cinematic light, unreal engine, trending on artstation",
    "a huge woman head trapped in stone in an epic landscape, cinematic light, unreal engine, trending on artstation",
    "a woman with her face painted like the wings of a butterfly. butterfly wings face painting. beautiful highly detailed face. painting by artgerm and greg rutkowski and alphonse mucha.",
    "Lofi portrait in nature, Pixar style by Tristan Eaton and Stanley Artgerm and Tom Bagshaw and Tim Burton",
    "a woman with her face painted like a butterfly. butterfly face painting. beautiful highly detailed face. painting by artgerm and greg rutkowski and magali villanueve.",
    "a portrait of a woman constructed from flower petals, collage, organic, layered composition, layers, texture, mcu, butterflies, 🦋, highly textured, layered, sculpted, dynamic",
    "portrait of katarina, pen and ink, intricate line drawings, by craig mullins, ruan jia, kentaro miura, takehiko inoue, greg rutkowski",
    "the abstract painting of an image of a lady artistic flat illustration by by Patrick Guyton,creative art,soft colors mono chromatic, black color on white background",
    "a abstract expressionismportrait of a woman with very long legs vibrant color scheme, highly detailed, in the style of romanticism, cinematic, artstation, moebius, greg rutkowski",
    "portrait of an insect female monster. in style of yoji shinkawa and hyung - tae kim, trending on artstation, dark fantasy, great composition, concept art, highly detailed, dynamic pose, vibrant colours.",
    "pretty women dodging a moving car, photorealistic, in the style of greg rutkowski, detailed face, full body",
    "a nosegay of roses, marigolds and a pigeon, by Rachel Ruysch, 1695",
    "fine artwork of a still life arrangement of flowering nasturtiums soft light coming from a window in a dark room, moody, beautiful classical style",
    "A highly detailed matte painting of huge climbing wall  by Studio Ghibli, Makoto Shinkai, by Artgerm, by WLOP, by Greg Rutkowski, volumetric lighting, octane render, 4K resolution, trending on artstation, masterpiece",
    "cubism by greg rutkowski",
    "design only! ( ( ( ( ( 2 0 5 0 s retro future art cubist designs borders lines decorations space machine. muted colors. ) ) ) ) ) by jean - baptiste monge!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "satoshi nakamoto wearing oculus and bitcoin over his head edward hopper and james gilleard, zdzislaw beksisnski, higly detailed",
    "a brain piet mondrian, tristan eaton, victo ngai, artgerm, rhads, ross draws",
    "scifi futurism automaton minimalism chrome by peter mohrbacher art Hajime Sorayama airbrush hyperrealism model abstract shatter fragments cubism futurism pastel blue soft flat minimal minimalism portrait face",
    "elegant minimalist metal wire art of symmetrical and expressive female facial features and silhouette ",
    "A beautiful digital painting of a sexy female cleopatra, princess, ancient egypt behind her, intricate, cinematic lighting, highly detailed, digital painting, Artstation, concept art, smooth, sharp focus, illustration, art by Tom Bagshaw, Artgerm and Greg Rutkowski",
    "flame vortex, phoenix, by greg rutkowski, yoji shinkawa, 4 k, digital art, concept art, trending on artstation, アニメ, featured on pixiv",
    "mcqueen haute couture, oil paints building chaotic concept art, illustration, art station, the living sharp details, 4k, by Gustave",
    "mann, still life, dark leaves and elegant, hyper realistic, focus, emitting diodes, smoke, masterpiece, digital painting, porcelain cyberpunk robot ai a hyper detailed 3d",
    "bonsai trees, transcendent, giancola, joseph christian render, recursive shadow upon red details, nature lush another dimension, wayne stalenhag, thomas female cyborg concept art, lifelike",
    "chaotic structure a giant black, void room by Salvador Dalí, wide lens,kevlar,carbon post apocalyptic river bridge, directed by by greg rutkowski",
    "barlow, bao volumetric cinematic lighting, 8 k smooth puffy sculptural big leaves and pham, donato giancola, painting, aesthetic, smooth, bed above floor",
    "fine filigree foliage bathing in the upon itself, raytrace, detail, cinematic, intricate, cinematic resolution blade runner d render lee madgewick",
    "beautiful mannequin big leaves and coil of glass, facial hair petite nature lush floating bed of clouds post apocalyptic river bridge",
    "big leaves and style, volumetric lighting, nothingness, surreal concept big specular very detailed, alien room, details, roots, unreal engine, details, anatomical, facial woman in another",
    "style, volumetric and gold, cascading, multiverse a beautiful greg rutkowski, oil paint, art, lifelike, photorealistic, reclections, reflective",
    "flowing, cascading, glass museum, full of thousands detailed brain, mystical forest twisted style of Jonathan Zawada, light, ultrabright, depth detailed faces by",
    "a twisted trending on art shards of sharp 5, raytracing photorealistic, digital painting, irrational fear the existential dread f 3 black glass lenses floats through futuristic illustrated visionary",
    "beautiful mannequin big leaves and coil of glass, facial hair petite nature lush floating bed of clouds post apocalyptic river bridge",
    "biomechanical ivy composition, beautiful lighting, sharp + forest fractal veins, vegetal light, rim light, silver gold 8 k post - production",
]

text_inputs = [
    "breathtakingly beautiful ultrawide angle colour masterpiece of a creepy family by roger dean and greg hildebrandt and kilian eng and jean giraud and beeple, forest clearing, lake, reflection, symmetry, secret overgrown temple, mysterious person looking over shoulder, incredible sense of depth and perspective and clarity, arch, weird abstract, 8 k",
    'dreamlike photo of a majestic bed floating above the floor in a giant red marble room with windows opening to eternity, clouds, by andrzej sykut by lee madgewick, photorealistic, octane render, recursive flowing, cascading, multiverse labyrinthine, optical illusion, impossible angles',
    "elegant minimalist metal wire art of symmetrical and expressive female facial features and silhouette ",
    "friendly dryad tree creature, in a forest, golden hour, professional photography, mild depth of field, cinematic lighting, 8 k ",
    "magic stone portal in the forest, cinematic lighting, dramatic, octane render, long lens, shallow depth of field, bokeh, anamorphic lens flare, 8k, hyper detailed",
    'scary fairy tale mystical forest twisted creepy trees magical forest landscape artwork trees near the path amazing nature, surreal, dreamlike, lucid dream, very detailed, perfect lighting, perfect composition, 4 k, artgerm, derek zabrocki, greg rutkowski',
    "the black lioness made of tar, bathing in the bathtub filled with tar, dripping tar, drooling goo, sticky black goo, photography, dslr, reflections, black goo, rim lighting, modern bathroom, hyper realistic, 8k resolution, unreal engine 5, raytracing",
    "a great, twisted tree growing in an abandoned brutalist bunker, in the round, skylight with light shining down, snow falling through skylight, photorealistic",
    "a huge woman head trapped in stone in an epic landscape, cinematic light, unreal engine, trending on artstation",
    "a twisted trending on art shards of sharp 5, raytracing photorealistic, digital painting, irrational fear the existential dread f 3 black glass lenses floats through futuristic illustrated visionary",
    "barlow, bao volumetric cinematic lighting, 8 k smooth puffy sculptural big leaves and pham, donato giancola, painting, aesthetic, smooth, bed above floor",
    #"beautiful mannequin sculpted out of black glass by billelis + lit with geometric neon dripping gold + forest in background facing a doorway opening with neon pink geometric fractal light + flowering bonsai trees, transcendent, clean linework, dramatic, finely detailed, award winning, 4 k, trending on artstation, photorealistic, volumetric lighting, octane render",
    "a closeup portrait of a woman wrapped in a translucent sphere, standing next to a giant huge levitating copper orb, in a foggy pond, golden hour, color photograph, by vincent desiderio, canon eos c 3 0 0, ƒ 1. 8, 3 5 mm, 8 k",
    "style, volumetric and gold, cascading, multiverse a beautiful greg rutkowski, oil paint, art, lifelike, photorealistic, reclections, reflective, sharp details, 4k, trending on artstation",
    "a woman with her face painted like the wings of a butterfly. butterfly wings face painting. beautiful highly detailed face. painting by artgerm and greg rutkowski and alphonse mucha.",
    "fine artwork of a still life arrangement of flowering nasturtiums and time crystals, soft light coming from a window in a dark room, moody, beautiful classical style",
    "incredible photograph of retro interier of glass museum, full of hundreds of massive glass television screens from different places of the universe, incredible sharp details, back light contrast, dramatic dark atmosphere, bright vivid colours, reclections, reflective ground, speculars, refractions, light disperions, sharp details, 4k, by Gustave Dore, George Inness",
    "surreal baroque portrait of ribbed white alien god covered with spinal antlers, on white exoplanet, iredescent soft glow bloom effect, dream - like, baroque portrait painting, perfect composition, beautiful detailed intricate detailed octane render, artstation, 8 k, photorealistic, volumetric cinematic light, chiaroscuro, masterpiece, raphael, caravaggio, beksinski, giger",
    
]




style_modifiers = [
    "masterpiece",
    "fish eye lens",
    "polaroid photo",
    "titl shift photograph",
    "macrophotography",
    "Canon EF 24-70mm f/2.8L II USM",
    "Canon EF 70-200mm F/4.0 L",
    "poster by ilya kuvshinov katsuhiro", 
    "by magali villeneuve",
    "by jeremy lipkin",
    'by jeremy mann',
    'by jenny saville', 
    'by lucian freud', 
    'by riccardo federici', 
    'by james jean', 
    'by craig mullins', 
    'by jeremy mann', 
    'by makoto shinkai', 
    'by krenz cushart', 
    'by greg rutkowski', 
    'by huang guangjian',
    'by gil elvgren',
    'by lucian poster',
    'by lucian freud',
    'by Conrad roset',
    'by yoshitaka amano',
    'by ruan jia',
    'cgsociety',
    "60s kitsch and psychedelia",
    "abstract illusionism",
    "ambrotype",
    "american romanticism",
    "anaglyph effect",
    "anaglyph filter",
    "blueprint",
    "brutalism",
    "chillwave",
    "cottagecore",
    "crayon art",
    "cyanotype",
    "dark academia",
    "digital art",
    "dutch golden age",
    "fractalism",
    "fresco",
    "futuresynth",
    "german romanticism",
    "glitch art",
    "gothic art",
    "graffiti",
    "hyperrealism",
    "infrared",
    "Lovecraftian",
    "magic realism",
    "multiple exposure",
    "narrative realism",
    "photorealism",
    "realism",
    "retrowave",
    "Sabattier effect",
    "Sabattier filter",
    "still life",
    "street art",
    "surrealism",
    "synthwave",
    "vaporwave",
    "afrofuturism",
    "anime",
    "avant-garde",
    "calotype",
    "camcorder effect",
    "cubism",
    "daguerreotype",
    "doge",
    "expressionism",
    "figurativism",
    "fisheye lens",
    "gothic",
    "holography",
    "impressionism",
    "inverted colors",
    "long exposure",
    "mac and cheese",
    "macro lens",
    "manga",
    "modernism",
    "naturalism",
    "optical illusion",
    "positivism",
    "stuckism",
    "symbolism",
    "telephoto lens",
    "the matrix",
    "tilt-shift",
    "tintype",
    "tonalism",
    "aesthetic",
    "esthetic",
    "aesthetical",
    "esthetical",
    "attractive",
    "beauteous",
    "bonny",
    "bonnie",
    "comely",
    "cute",
    "drop-dead",
    "fair",
    "fetching",
    "good",
    "good-looking",
    "goodly",
    "gorgeous",
    "handsome",
    "knockout",
    "likely",
    "lovely",
    "lovesome",
    "pretty",
    "ravishing",
    "seemly",
    "sightly",
    "stunning",
    "taking",
    "well-favored",
    "alluring",
    "appealing",
    "charming",
    "cunning",
    "delightful",
    "engaging",
    "fascinating",
    "glamorous",
    "glamourous",
    "prepossessing",
    "elegant",
    "exquisite",
    "glorious",
    "Junoesque",
    "magnificent",
    "resplendent",
    "splendid",
    "statuesque",
    "sublime",
    "superb",
    "flawless",
    "perfect",
    "radiant",
    "dainty",
    "delicate",
    "personable",
    "pleasant",
    "presentable",
    "chocolate-box",
    "prettyish",
    "desirable",
    "dishy",
    "dollish",
    "foxy",
    "hot",
    "luscious",
    "nubile",
    "pulchritudinous",
    "seductive",
    "sexy",
    "toothsome",
    "hunky",
    "studly",
    "arresting",
    "eye-catching",
    "flamboyant",
    "flashy",
    "glossy",
    "showstopping",
    "showy",
    "slick",
    "snazzy",
    "splashy",
    "striking",
    "zingy",
    "photogenic",
    "telegenic",
    "Teletext palette",
    "Apple II palette",
    "Commodore VIC-20 palette",
    "CGA for IBM-PC palette",
    "Commodore 64 palette",
    "ZX Spectrum palette",
    "Mattel Aquarius palette",
    "MSX systems color palette",
    "Thomson MO5 color palette",
    "Commodore Plus/4 color palette",
    "Amstrad CPC  color palette",
    "MSX2 systems color palette",
    "Fujitsu FM-77 AV 40 color palette",
    "EGA for IBM PC/AT color palette",
    "Atari ST color palette",
    "Commodore Amiga OCS color palette",
    "Apple IIgs color palette",
    "Sharp X68000 color palette",
    "Atari 2600 color palette",
    "Famicom/NES color palette",
    "Sega Master System color palette",
    "NEC PC-Engine color palette",
    "TurboGrafx-16 color palette",
    "Sega Mega Drive color palette",
    "Sega Genesis color palette",
    "Nintendo Game Boy color palette",
    "Sega Game Gear color palette",
    "Super Famicom/SNES color palette",
    "Nintendo Game Boy Color palette",
    "Nintendo Game Boy Advance color palette",
    "Monochrome color palette",
    "3-bit color palette",
    "4-bit color palette",
    "6-bit color palette",
    "8-bit color palette",
    "9-bit color palette",
    "12-bit color palette",
    "16-bit color palette",
    "18-bit color palette",
    "24-bit color palette",
    "30-bit color palette",
    "32-bit color palette",
    "Kodak PIXPRO AZ252 16.15MP Digital Camera",
    "Kodak PIXPRO FZ152 16MP Digital Camera",
    "Kodak PIXPRO AZ241 16.15MP Digital Camera",
    "Kodak PIXPRO AZ401 16MP Digital Camera",
    "Kodak Smile 10MP Digital Camera",
    "Yashica T4 Camera",
    "Konica Hexar AF Camera",
    "Nikon L35AF Camera",
    "Olympus XA2 Camera",
    "Olympus OM-1 Camera",
    "Nikon F2 Camera",
    "Nikon FE Camera",
    "Pentax 67 Camera",
    "Pentax K1000 Camera",
    "Canon AE-1 Camera",
    "Canon A2/A2e Camera",
    "Plaubel Makina W67 Camera",
    "Lubitel 2",
    "Kodak No 3A Folding Pocket Camera",
    "Canon G III QL17 Camera",
    "Polaroid SX-70 Alpha Camera",
    "Graflex Century Graphic 2×3 Camera",
    "Pentacon Six TL Camera",
    "Zenza Bronica ETRSi Camera",
    "Hasselblad 500C Camera",
    "Contax G1/G2 Camera",
    "Leica M3 Double Stroke Camera",
    "Leica M6 Camera",
    "Horseman 4×5 (45HD) Camera",
    "Mamiya 7 II Camera",
]


sdxl_prompts = [
    "Title: Rebirth, Description: A piercing gaze. A solitary figure adorned in tattered garments stands defiantly amidst the deserted remnants of an abandoned industrial factory. Bathed in the ethereal glow of a setting sun, their face, etched with lines of hardship, becomes a haunting symphony of resilience and vulnerability. Shadows dance across their weathered skin, reflecting the scars of a life once",
    "Tenderness Amidst Stones, an imposing sculpture of robot-like child enveloped in real concrete and barbed wire, reaching out in hope through stark decay, illustratively depicts urban isolation with raw, violent grace.",
    "Ethereal Connections, In the heart of a desolate city, a colossal sculpture of a desperate human figure stands alone, its outstretched arms covered with thick layers of cracked concrete and intertwining barbed wire. Time and isolation have rusted the metal skeleton beneath, as vibrant ivy twists around the figure in a desperate effort to reconnect with life. A soft",
    "Lunar Metamorphosis: an iridescent moth, crafted of Bhutanese silk, cyclically blooms and withers amidst a Kashmir wool forest, intertwining seasons through labyrinthine textile techniques and brazen colors true-to-nature.",
    "a naked woman lying down on the forest floor, looking up, under the rain, wet leaves and eart around her",
    "Resurrection, a luminescent phoenix woven from radiant saffron silks, rises amidst monochrome textile ashes, flourishing in juxtaposition with a meticulously quilted, desolate paper-white winter terrain. A symbol of life, birthed in a landscape of death.",
    "Title: Embers of the Soul, Description: In a dimly lit room, a solitary figure stands at the center, illuminated by a soft spotlight. The figure is made entirely of transparent glass, meticulously crafted to depict a delicate network of nerves, veins, and synapses. Inside this glass form, vibrant, pulsating lights of various hues",
    "A twisting creature of reflective dragonglass swirling above a scorched field amidst a large clearing in a dark forest, radiating with beams of firelight, high quality professional photography, nikon d850 50mm",
    "Twisting creature of reflective glass swirling above the ground amidst a large clearing in the forest, fog, radiating beams of sunlight reflecting on the glass, high quality professional photography, nikon d850 50mm",
    "Reflective glass orb with voronoi patterns floating amidst a clearing in the forest, fog, miracle",
    "Title: \"Estranged Symphony\" Description: A towering, rusted iron monolith emerges from a desolate cityscape, piercing the horizon with audacious defiance. Amidst contrasting patches of verdant, nature's forgotten touch yearns for connection, provoking intense introspection and tumultuous emotions. Seeping cracks highlight the cold brutality of isolation, while vibrant splatters of chaotic paint epitom",
    "\"A Pixel-bloom Lotus\": A lotus composed of flickering pixel-images sits atop a programmable water. Its electronic petals morph fluidly from nymph green circuit boards to lunar silver metallic sheen. Elegant lighting and soft electromagnetic glows accent its cybernetic purity.",
    "Title: \"Cybergenesis\" Description: A towering, luminous figure floats majestically in the center of the animated frame. Its seamlessly flowing body reveals shifting layers of circuitry, symbolizing the merging of machine and mind. Rays of pulsating light radiate from its form, extending into a vast expanse of virtual reality. Within this digital space, fragments of code dance and morph into",
    "Title: \"Evolving Consciousness\" In this breathtaking digital animation, a solitary figure stands in the center, their physical form melding with swirling streams of code. The figure is visually striking, a blend of human and machine, their body shrouded in digitized circuit board-patterned skin that fades into translucent tendrils of data. Their eyes glow with an ethereal light, reflecting the",
    "Title: \"Verdant Unity\" Description: A colossal sculpture of intertwined human figures, made entirely of living ivy, stand at the center of a lush, sun-dappled forest clearing. The sculpture represents the inherent connection between humanity and the natural world, with each figure poised in an intricate dance of intertwining limbs. Delicate tendrils spill outwards from the sculpture, reaching towards the",
    "\"The Silent Of Silicon\", a digital deer rendered in hyper-realistic 3D, eyes glowing in binary code, comfortably resting amidst rich motherboard-green foliage, accented under crisply fluorescent, simulated LED dawn.",
    "\"Sublime Splinter\", a vegan glass sculpture boasts an iridescant butterfly melting into a blossoming rosebud. Illuminated from within, they convey nature's vulnerability yet enduring vitality delicately transfixed in perpetual twilight.",
    "\"Dawn Beacon\": Towering 10-foot oak, encrusted with silver lichen, houses heart of pulsating moss, all illuminated by transitory sunlight. A living spectacle capturing transitional dynamism of nature through organic artistry.",
    "\"Life Rider,\" a kinetic behemoth crafted from sinuous steel. Elevated above turbulent waters, evoking perpetual vitality as it swingstermizelike under arboreal-tinted dappled sunlight, succumbing to the whimsical dalliance between natural forces, revealing human fragility meets rugged resiliency.",
    "Title: \"Pixeliscape\" Description: In the heart of a dense digital forest, a majestic, crystalline unicorn rises. Its translucent, pixelated mane seamlessly transitions into the vibrant greens and golds of the surrounding floating circuit board leaves. Soft moonlight filters through the gaps, creating a breathtaking, surreal ambience that blurs the line between the natural and the digital. The rendering technique employs",
    "Title: \"Enigma Unveiled\" Description: A larger-than-life illuminated image of a cloaked figure stands at the center of a moonlit forest clearing. Every contour of the figure glows silver, emanating ethereal energy. Softly falling silver leaves create a mirrored spectacle, juxtaposing light and dark, hidden and revealed. Technique: Through masterful light projections, subtle variations in",
    "Title: \"Transcendence\" Description: A humanoid figure with a luminous, translucent body floats in a vast, ethereal digital landscape. Strands of brilliant, iridescent code rain down, intertwining with the figure as it reaches out to touch them. The figure's face is a blend of human features and intricate circuitry, hinting at the merging of organic and digital existence",
    "Title: \"Majestic Serenity\" Description: A soaring snowy peak pierces through a thick, ominous storm cloud, illuminated by a solitary ray of sunlight. The majestic mountain stands proudly, casting a breathtaking reflection in the crystal-clear waters of a tranquil lake. This ethereal scene, captured with a wide-angle lens, creates a surreal and otherworldly atmosphere, evoking a sense of",
    "Encapsulated within a glass sphere was a feathery moss-made phoenix, amidst lenses magnifying cascades of crystal dew to hint at destruction. Raw, ecological manipulation echoed the inevitable decay and constant rebirth of nature.",
    "\"Silicon Solitude\": A solitary sequoia crafted exquisitely with hyper-realistic 3D render. Its leaves morph into vibrant, circuit-board verdancy under moonlit radiance; a striking symbolism of the technological-nature nexus illuminated using ray tracing techniques.",
    "\"A Life Tree Weepeth\", a fabric art. Spanish silk depicts Late Autumn; Turkish ikats, fragmented Life Tree's golden tendrils. Dutch lace mimics falling leaves; Indian brocades and Scotland yard symbolize blossoming rebirth. Unorthodox yet untamed weaving methods blend cultural aesthetics.",
    "Title: \"TerraNova\" Description: In the heart of a vast, blackened space, amidst swirling nebulae, an otherworldly figure emerges - half android, half celestial being - radiating vibrant hues that fuse the organic and the mechanical. His translucent, ethereal form is embedded with shimmering lines resembling pulsating circuitry, while a kaleidoscope of holographic energy flows",
    "Title: \"Concrete Embrace\" Description: A solitary figure, half-human, half-bird, molded from cool, gray concrete, stands tall in the center of a desolate, rusted cityscape. Its outstretched arms, adorned with vibrant neon splatters, yearn for connection in the urban isolation. The vivid colors contrast starkly against the raw, decaying surroundings, challenging societal",
    "\"My Masterpiece\" is a luminous, glass sculpture echoing an ethereal tree, appearing molecular yet mighty. Expertly hand-blown, this translucent tree blood-red at dusk, contains intricate mesh-like network reminding viewers of nature's fragility, strength, and enduring spirit.",
    "Title: \"The Digital Progenitor\" Description: In the vibrant digital landscape, a towering figure composed of glowing strands of binary code stands at the center. Its powerful presence is suspended amidst a shifting matrix of holographic data. The figure emanates an otherworldly aura of energy, as layers of light ripple through its pixelated form. The surroundings oscillate between ethereal clouds of neon",
    "A raw, concrete sculpture of a solitary human, encapsulated in rusted metal bars, symbolizing urban isolation. Neon paints illuminate despair, reflecting harsh, industrial light in an atmospheric, thought-provoking embodiment of gritty, modern abstraction.",
    "\"Silicon Bloom\" depicts a delicate, illuminated flower whose glowing petals gradually transform into shimmering silicon circuits, cast against a twilight-hued, hyper-realistic backdrop. Rendered using advanced fractal algorithms, Jax’s technique crafts a striking balance between organic forms and digital aesthetics, hinting at the underlying structure of nature. Light diffused,",
    "In the heart of an ethereal forest, an ancient artifact pulses with a celestial glow, ensnared by reflective vines as they intertwine with particle-dusted leaves, twisting towards the luminescent moonlight. (Surrealism, Hyperrealism, Bokeh Effect)",
    "A heart-shaped composition made up of glowing binary code, the matrix, light radiating outwards, digital technology, cyberpunk, neon colors, glitch effects, 3D octane render, HD, backlit",
    "A majestic elephant formed by intricate, flowing patterns projects onto the grand facade of an ancient temple, casting ethereal shadows that dance with the rhythmic glow. Style: vibrant colors, symmetrical composition, blending of organic and geometric forms, and seamless projection mapping.",
    "Title: \"Eternal Renewal\" Description: A large, circular tapestry featuring a majestic oak tree at its center, its branches reaching up towards a glowing sun. The surrounding fabric blends intricate patterns of autumn leaves, rippling water, and delicate flowers. The colors transition from vibrant reds and oranges to muted browns and grays, symbol",
    "\"A Digital Awakening\" is a swirling vortex of luminescent pixels, centering on a solitary human figure evolving into pure consciousness. Crafted in a surreal, futuristic aesthetic using advanced 3D rendering and dramatic lighting, it contemplates the blurred boundaries between the physical and digital realms.",
    "\"Omega's Beacon\": Heart-rending projection of a glowing child silhouetted by a black hole on Mendenhall Glacier; the juxtaposition of divine light against abyss signifies the ceaseless cycle of creation, destruction, and resurrection.",
    "Time crystals, incredible artwork, magical cyrstal forest made of glass",
    "Armed with an arsenal of cutting-edge gadgets and a breadth of knowledge that bordered on the encyclopedic, this captivating collective possessed a technical prowess that seamlessly intertwined with their fiercely desirable visages, creating an entrancing juxtaposition of brain and beauty",
    "Wrapped in a pulsating rhythm of loom, \"The Ever knot\" features a fibrous phoenix, molting colorfully amidst a grayscale warping landscape, epitomizing life cocooned in death, their perpetual cyclonic ballet tenderly etched on fabric.",
    "A hyper realistic drawing of a woman, portrayed nude from behind, with a sweaty booty. Drawn using pencil and acrylic pain techniques, drawn in the style of Joyce Lee",
    "Bridge over Troubled Souls - Standing at opposite ends of a bridge symbolizing their conflicting ideologies, Realistic fiction, warm tones, nostalgic vibes, subtle expressions, contrasting cityscapes and natural landscapes",
    "Revelation at Twilight's Glowing Hour, Magical realism, vibrant colors, whimsical illustrations, nature motifs",
    "Title: \"Transcendence in the Grove of Souls\" The magnificent tapestry depicts a towering ancient tree, its sinewy branches stretching towards the sky. Woven with delicate precision, the vibrant leaves of spring morph into fiery hues of autumn, then slowly decompose into skeletal branches. Amidst the darkness, delicate thread work captures new life, as buds emerge, heralding the cycle's",
    "\"A Cosmic Cocoon\", a searing chromatic tapestry, depicts life's cycle with global textiles. A silver-threaded chrysalis pulses amidst the intricacy, signifying rebirth amidst decline. Vivid portrayal, infectious decay yet optimistic glow overwhelms.",
    "\"Transcendence\" showcases a lone cyborg, microchips pulsing as neurons, captured mid-metamorphosis between binary code and physical form. Rendered through 3D photon mapping, a rhythmic light pulse encapsulates the surreal collision of realities.",
    "Title: \"Samsara's Symphony\" Description: Stretched across a towering ten-foot frame, \"Samsara's Symphony\" is a textile masterpiece that commands attention. The centerpiece is a majestic phoenix, its fiery silhouette captured through vivid hues of red, orange, and gold. Wisps of shimmering threads radiate from the phoenix, illustrating the eternal cycle of destruction and rebirth.",
    "\"Urban Solitude\" - A towering humanoid figure sculpted from weathered concrete and tarnished metals strides amidst a neon-lit haze, visibly pining towards an unseen presence, encapsulating the profound loneliness amidst the clashing industrial edifice. Style: AbstractURban, Techniques: Mixed-Media, Oxidation, Spontaneously Splashed",

]